export const FETCH_BY_POKEMONS_REQEST = "FETCH_BY_POKEMONS_REQEST";
export const FETCH_BY_POKEMONS_SUCCESS = "FETCH_BY_POKEMONS_SUCCESS";
export const FETCH_BY_POKEMONS_ERROR = "FETCH_BY_POKEMONS_ERROR";
export const SEARCH_POKEMON_REQEST = "SEARCH_POKEMON_REQEST";
export const SEARCH_POKEMON_SUCCESS = "SEARCH_POKEMON_SUCCESS";
export const SEARCH_POKEMON_ERROR = "SEARCH_POKEMON_ERROR";
export const FETCH_ABILITIES_BY_POKEMON_REQEST =
  "FETCH_ABILITIES_BY_POKEMON_REQEST";
export const FETCH_ABILITIES_BY_POKEMON_SUCCESS =
  "FETCH_ABILITIES_BY_POKEMON_SUCCESS";
export const FETCH_ABILITIES_BY_POKEMON_ERROR =
  "FETCH_ABILITIES_BY_POKEMON_ERROR";
